server_ip: "0.0.0.0"
server_port: 30052
pose_topic: "milliampere/pose"
twist_topic: "milliampere/twist"
camera_ids: 
    - "F"
    - "FR"
    - "RR"
    - "RL"
    - "FL"
camera_prefix: "EO/"
camera_postfix: "/image_raw"
lidar_topic: "lidar/driver/velodyne_points"
radar_topic: "radar/driver/spokes"
